int pedirValidos(int minimo, int maximo);
void mostrarVector(int vector[], int SIZE);
void cargarVector(int vector[], int SIZE, int minimo, int maximo);
void mostrarPositivosYNegativos (int vector[], int SIZE);
void sumarPares(int vector[], int SIZE);
void mayorImpares(int vector[], int SIZE);
void mostrarPares(int vector[], int SIZE);
void mostrarNumerosEnPosicionesImpares (int vector[], int SIZE);
void ordenarPositivosAscendente(int vector[], int SIZE);
void ordenarNegativosDescendente(int vector[], int SIZE);
void mostrarNumerosRepetidos(int vector[], int SIZE);
